{
    # image encoder settings
    encoder_name: 'clip_resnet_large',
    adapter_config: {
        "mlp": {"adapter_type": "normal", "downsample_factor": 4},
        "attention": {"adapter_type": "normal", "downsample_factor": 8}
    },
    freeze_img_encoder: true,
    freeze_lm: true,

    # train settings
    batch_size: 32,
    train_steps: 150000,
    lr: 1.0e-4,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    warmup_num_steps: 100,
    image_enc_lr: null,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.0,
    image_size: 384,
   
    use_torch_amp: true,
    use_torch_grad_scaler: true,

    gradient_accumulation_steps: 32,
    zero_stage: 0,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'magma_frank_captions',
    train_dataset_dir: 'magma_frank_captions',
    eval_dataset_name: 'magma_frank_captions',
    eval_dataset_dir: null,

    ckpt_path: "magma_split_ckpt_frank",

    save: "magma_tune_frank_v1",
    load: "magma_tune_frank_v1",
    load_optimizer: true,

    eval_batch_size: 2,
    eval_every: 50,
    eval_steps: 200,
    save_every: 300,

}
