{
    # image encoder settings
    encoder_name: 'clip_resnet_large',
    adapter_config: {
        "mlp": {"adapter_type": "normal", "downsample_factor": 4},
        "attention": {"adapter_type": "normal", "downsample_factor": 8},
    },
    freeze_img_encoder: false,
    freeze_lm: true,

    # train settings
    batch_size: 64,
    train_steps: 1025,
    lr: 1.0e-4,
    min_lr: 1.0e-6,
    attn_adapter_lr: 4.0e-4,
    lr_decay_iters: 975,
    warmup_num_steps: 50,
    image_enc_lr: 1.0e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.0,
    image_size: 384,

    use_torch_amp: false,
    use_torch_grad_scaler: false,
    use_apex_amp: false,

    gradient_accumulation_steps: 2,
    zero_stage: 0,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'magma_frank_captions_heldout',
    train_dataset_dir: 'magma_frank_captions_heldout',
    eval_dataset_name: 'magma_frank_captions_heldout',
    eval_dataset_dir: 'magma_frank_captions_heldout',

    ckpt_path: "magma_split_ckpt_frank",

    save: "magma_tune_frank_arj_xtn11p1_frombase_attn_imgenc",
    load: "",
    load_optimizer: true,

    eval_batch_size: 2,
    eval_every: 5000000,
    eval_steps: 200,
    save_every: 3000,
}
