{
    # image encoder settings
    encoder_name: 'clip_resnet_large',
    adapter_config: {
        "mlp": {"adapter_type": "normal", "downsample_factor": 4},
        "attention": {"adapter_type": "normal", "downsample_factor": 8}
    },
    freeze_img_encoder: true,
    freeze_lm: true,

    # train settings
    batch_size: 16,
    train_steps: 150000,
    lr: 1.0e-4,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    warmup_num_steps: 50,
    image_enc_lr: null,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.0,
    image_size: 384,

    gradient_accumulation_steps: 16,
    zero_stage: 0,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'xmas_384_supplement_incremental2',
    train_dataset_dir: 'dataset_magma_2',
    eval_dataset_name: 'xmas_384_supplement_incremental1',
    eval_dataset_dir: 'dataset_magma',

    optimizer_name: "Adam",

    ckpt_path: "magma_split_ckpt",

    save: "magma_tune_v0",
    load: "",
    load_optimizer: false,

    eval_every: 50,
    eval_steps: 300,
    save_every: 300,

}
